# Generated by Django 4.1 on 2022-11-28 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'PaymentMaster',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/Supplier/')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_photo', models.ImageField(default='no_img.jpg', upload_to='images/product/')),
                ('prod_price', models.IntegerField(default=200)),
                ('prod_quantity', models.IntegerField(default=1)),
                ('prod_description', models.CharField(max_length=100)),
                ('prod_treatment', models.CharField(max_length=100)),
                ('prod_compostion', models.CharField(max_length=100)),
                ('prod_type', models.CharField(max_length=50)),
                ('prod_exp', models.DateField(default=datetime.datetime.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.category')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.supplier')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
