# Generated by Django 4.1 on 2022-11-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_exp',
            field=models.CharField(max_length=50),
        ),
    ]
