# Generated by Django 4.1 on 2022-11-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_product_prod_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='photo',
        ),
    ]
