# Generated by Django 4.1 on 2022-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_supplier_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.EmailField(max_length=25)),
                ('messege', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
