# Generated by Django 4.1 on 2022-12-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Shipping',
            },
        ),
    ]
