# Generated by Django 4.1 on 2022-11-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='cake',
            new_name='medicine',
        ),
    ]
