# Generated by Django 4.1 on 2022-12-07 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_supplier_photo'),
        ('User', '0002_rename_cake_mycart_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1000)),
                ('dateOfOrder', models.DateTimeField(default=datetime.datetime.now)),
                ('details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
